apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "anycable.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ .Release.Name | quote }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ template "anycable.name" . }}
    release: {{ .Release.Name | quote }}
  type: ClusterIP
