{{- range $host := .Values.ingress.hosts }}
{{- if $host.tls }}
{{- if (and $host.tls.key $host.tls.crt) }}
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ $host.name }}-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ $host.tls.crt | b64enc | quote }}
  tls.key: {{ $host.tls.key | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
